apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-api-service
  namespace: development
spec:
  selector:
    app: weather-forecast-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
